#author:  Allison R. Wright
#purpose:  Practice formatting strings

print(f"Please enter the following information:")

surname = input("Last Name:")
firstname = input("First Name:")
jobtitle = input("Job Title:")
idNumber = input("ID Number:")
email = input("Email Address:")
phone = input("Phone Number:")
formattedPhone = f"({phone[0:3]}) {phone[3:6]}-{phone[6:]}"
hair = input("Hair:")
eyes = input("Eyes:")
month = input("Month:")
training = input("Training:")

print()
print(f"First name: {firstname.capitalize()}")
print(f"Last name: {surname.capitalize()}")
print(f"Email address: {email}")
print(f"Phone number: {formattedPhone}")
print(f"Job title: {jobtitle}")
print(f"ID Number: {idNumber}")

print(f"The ID Card is:")
print(f"----------------------------------------")
print(f"{surname.upper()}, {firstname.capitalize()}")
print(f"{jobtitle.title()}")
print(f"ID: {idNumber}")
print()
print(f"{email.lower()}")
print(f"{formattedPhone}")
print(f"----------------------------------------")

print(f"Challenge activity")
print()
print(f"The ID Card is:")
print(f"----------------------------------------")
print(f"{surname.upper()}, {firstname.capitalize()}")
print(f"{jobtitle.title()}")
print(f"ID: {idNumber}")
print()
print(f"{email.lower()}")
print(f"{formattedPhone}")
print()
print(f"Hair: {hair.capitalize()}  Eyes: {eyes.capitalize()}")
print(f"Month: {month.capitalize()}  Training: {training.capitalize()}")
print(f"----------------------------------------")
